# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 730)
        self.robot_parameters = QtWidgets.QGroupBox(Form)
        self.robot_parameters.setGeometry(QtCore.QRect(60, 190, 341, 291))
        self.robot_parameters.setObjectName("robot_parameters")
        self.robot_parameters_box = QtWidgets.QGroupBox(self.robot_parameters)
        self.robot_parameters_box.setGeometry(QtCore.QRect(70, 30, 191, 51))
        self.robot_parameters_box.setObjectName("robot_parameters_box")
        self.l1_input = QtWidgets.QLineEdit(self.robot_parameters_box)
        self.l1_input.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.l1_input.setObjectName("l1_input")
        self.l2_input = QtWidgets.QLineEdit(self.robot_parameters_box)
        self.l2_input.setGeometry(QtCore.QRect(130, 20, 31, 20))
        self.l2_input.setObjectName("l2_input")
        self.l1_label = QtWidgets.QLabel(self.robot_parameters_box)
        self.l1_label.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.l1_label.setObjectName("l1_label")
        self.l2_label = QtWidgets.QLabel(self.robot_parameters_box)
        self.l2_label.setGeometry(QtCore.QRect(110, 20, 16, 16))
        self.l2_label.setObjectName("l2_label")
        self.joint_masses = QtWidgets.QGroupBox(self.robot_parameters)
        self.joint_masses.setGeometry(QtCore.QRect(70, 100, 191, 51))
        self.joint_masses.setObjectName("joint_masses")
        self.m1_input = QtWidgets.QLineEdit(self.joint_masses)
        self.m1_input.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.m1_input.setObjectName("m1_input")
        self.m2_input = QtWidgets.QLineEdit(self.joint_masses)
        self.m2_input.setGeometry(QtCore.QRect(130, 20, 31, 20))
        self.m2_input.setObjectName("m2_input")
        self.m2_label = QtWidgets.QLabel(self.joint_masses)
        self.m2_label.setGeometry(QtCore.QRect(110, 20, 16, 16))
        self.m2_label.setObjectName("m2_label")
        self.m1_label = QtWidgets.QLabel(self.joint_masses)
        self.m1_label.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.m1_label.setObjectName("m1_label")
        self.torque_limits = QtWidgets.QGroupBox(self.robot_parameters)
        self.torque_limits.setGeometry(QtCore.QRect(70, 160, 191, 101))
        self.torque_limits.setObjectName("torque_limits")
        self.input1_min_input = QtWidgets.QLineEdit(self.torque_limits)
        self.input1_min_input.setGeometry(QtCore.QRect(80, 20, 21, 20))
        self.input1_min_input.setObjectName("input1_min_input")
        self.input1_max_input = QtWidgets.QLineEdit(self.torque_limits)
        self.input1_max_input.setGeometry(QtCore.QRect(150, 20, 21, 20))
        self.input1_max_input.setObjectName("input1_max_input")
        self.input2_min_input = QtWidgets.QLineEdit(self.torque_limits)
        self.input2_min_input.setGeometry(QtCore.QRect(80, 60, 21, 20))
        self.input2_min_input.setObjectName("input2_min_input")
        self.input2_max_input = QtWidgets.QLineEdit(self.torque_limits)
        self.input2_max_input.setGeometry(QtCore.QRect(150, 60, 21, 20))
        self.input2_max_input.setObjectName("input2_max_input")
        self.input1_label = QtWidgets.QLabel(self.torque_limits)
        self.input1_label.setGeometry(QtCore.QRect(20, 20, 21, 16))
        self.input1_label.setObjectName("input1_label")
        self.input2_label = QtWidgets.QLabel(self.torque_limits)
        self.input2_label.setGeometry(QtCore.QRect(20, 60, 21, 16))
        self.input2_label.setObjectName("input2_label")
        self.input1_min_label = QtWidgets.QLabel(self.torque_limits)
        self.input1_min_label.setGeometry(QtCore.QRect(50, 20, 21, 16))
        self.input1_min_label.setObjectName("input1_min_label")
        self.input2_min_label = QtWidgets.QLabel(self.torque_limits)
        self.input2_min_label.setGeometry(QtCore.QRect(50, 60, 21, 16))
        self.input2_min_label.setObjectName("input2_min_label")
        self.input1_max_label = QtWidgets.QLabel(self.torque_limits)
        self.input1_max_label.setGeometry(QtCore.QRect(120, 20, 31, 16))
        self.input1_max_label.setObjectName("input1_max_label")
        self.input2_max_label = QtWidgets.QLabel(self.torque_limits)
        self.input2_max_label.setGeometry(QtCore.QRect(120, 60, 31, 16))
        self.input2_max_label.setObjectName("input2_max_label")
        self.simulation_parameters = QtWidgets.QGroupBox(Form)
        self.simulation_parameters.setGeometry(QtCore.QRect(410, 20, 401, 461))
        self.simulation_parameters.setObjectName("simulation_parameters")
        self.path_dynamics_section = QtWidgets.QGroupBox(self.simulation_parameters)
        self.path_dynamics_section.setGeometry(QtCore.QRect(10, 160, 381, 131))
        self.path_dynamics_section.setObjectName("path_dynamics_section")
        self.s_min_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.s_min_input.setGeometry(QtCore.QRect(60, 20, 21, 20))
        self.s_min_input.setObjectName("s_min_input")
        self.s_max_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.s_max_input.setGeometry(QtCore.QRect(310, 20, 21, 20))
        self.s_max_input.setObjectName("s_max_input")
        self.s_min_label = QtWidgets.QLabel(self.path_dynamics_section)
        self.s_min_label.setGeometry(QtCore.QRect(20, 20, 41, 20))
        self.s_min_label.setObjectName("s_min_label")
        self.s_max_label = QtWidgets.QLabel(self.path_dynamics_section)
        self.s_max_label.setGeometry(QtCore.QRect(270, 20, 31, 16))
        self.s_max_label.setObjectName("s_max_label")
        self.s_increment_label = QtWidgets.QLabel(self.path_dynamics_section)
        self.s_increment_label.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.s_increment_label.setObjectName("s_increment_label")
        self.s_increment_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.s_increment_input.setGeometry(QtCore.QRect(190, 20, 21, 20))
        self.s_increment_input.setObjectName("s_increment_input")
        self.advanced_sim_button = QtWidgets.QPushButton(self.path_dynamics_section)
        self.advanced_sim_button.setGeometry(QtCore.QRect(260, 90, 91, 31))
        self.advanced_sim_button.setObjectName("advanced_sim_button")
        self.sdot_min_label = QtWidgets.QLabel(self.path_dynamics_section)
        self.sdot_min_label.setGeometry(QtCore.QRect(10, 60, 51, 20))
        self.sdot_min_label.setObjectName("sdot_min_label")
        self.sdot_increment_label = QtWidgets.QLabel(self.path_dynamics_section)
        self.sdot_increment_label.setGeometry(QtCore.QRect(130, 60, 51, 20))
        self.sdot_increment_label.setObjectName("sdot_increment_label")
        self.sdot_increment_label_2 = QtWidgets.QLabel(self.path_dynamics_section)
        self.sdot_increment_label_2.setGeometry(QtCore.QRect(250, 60, 51, 20))
        self.sdot_increment_label_2.setObjectName("sdot_increment_label_2")
        self.sdot_min_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.sdot_min_input.setGeometry(QtCore.QRect(60, 60, 21, 20))
        self.sdot_min_input.setObjectName("sdot_min_input")
        self.sdot_increment_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.sdot_increment_input.setGeometry(QtCore.QRect(190, 60, 21, 20))
        self.sdot_increment_input.setObjectName("sdot_increment_input")
        self.sdot_max_input = QtWidgets.QLineEdit(self.path_dynamics_section)
        self.sdot_max_input.setGeometry(QtCore.QRect(310, 60, 21, 20))
        self.sdot_max_input.setObjectName("sdot_max_input")
        self.Controller_section = QtWidgets.QGroupBox(self.simulation_parameters)
        self.Controller_section.setGeometry(QtCore.QRect(10, 300, 381, 131))
        self.Controller_section.setObjectName("Controller_section")
        self.advanced_control_button = QtWidgets.QPushButton(self.Controller_section)
        self.advanced_control_button.setGeometry(QtCore.QRect(260, 70, 91, 31))
        self.advanced_control_button.setObjectName("advanced_control_button")
        self.time_optimal_control_cb = QtWidgets.QCheckBox(self.Controller_section)
        self.time_optimal_control_cb.setGeometry(QtCore.QRect(20, 30, 161, 21))
        self.time_optimal_control_cb.setChecked(True)
        self.time_optimal_control_cb.setTristate(False)
        self.time_optimal_control_cb.setObjectName("time_optimal_control_cb")
        self.path_characteristics = QtWidgets.QGroupBox(self.simulation_parameters)
        self.path_characteristics.setGeometry(QtCore.QRect(10, 20, 381, 131))
        self.path_characteristics.setObjectName("path_characteristics")
        self.advanced_path_button = QtWidgets.QPushButton(self.path_characteristics)
        self.advanced_path_button.setGeometry(QtCore.QRect(250, 90, 101, 31))
        self.advanced_path_button.setObjectName("advanced_path_button")
        self.straightline_definition_settings = QtWidgets.QGroupBox(self.path_characteristics)
        self.straightline_definition_settings.setGeometry(QtCore.QRect(10, 30, 211, 91))
        self.straightline_definition_settings.setObjectName("straightline_definition_settings")
        self.x2_label = QtWidgets.QLabel(self.straightline_definition_settings)
        self.x2_label.setGeometry(QtCore.QRect(20, 50, 21, 16))
        self.x2_label.setObjectName("x2_label")
        self.y1_input = QtWidgets.QLineEdit(self.straightline_definition_settings)
        self.y1_input.setGeometry(QtCore.QRect(100, 20, 31, 21))
        self.y1_input.setObjectName("y1_input")
        self.y2_input = QtWidgets.QLineEdit(self.straightline_definition_settings)
        self.y2_input.setGeometry(QtCore.QRect(100, 50, 31, 21))
        self.y2_input.setObjectName("y2_input")
        self.y1_label = QtWidgets.QLabel(self.straightline_definition_settings)
        self.y1_label.setGeometry(QtCore.QRect(80, 20, 16, 16))
        self.y1_label.setObjectName("y1_label")
        self.y2_label = QtWidgets.QLabel(self.straightline_definition_settings)
        self.y2_label.setGeometry(QtCore.QRect(80, 50, 16, 16))
        self.y2_label.setObjectName("y2_label")
        self.x1_label = QtWidgets.QLabel(self.straightline_definition_settings)
        self.x1_label.setGeometry(QtCore.QRect(20, 20, 21, 16))
        self.x1_label.setObjectName("x1_label")
        self.x1_input = QtWidgets.QLineEdit(self.straightline_definition_settings)
        self.x1_input.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.x1_input.setObjectName("x1_input")
        self.x2_input = QtWidgets.QLineEdit(self.straightline_definition_settings)
        self.x2_input.setGeometry(QtCore.QRect(40, 50, 31, 21))
        self.x2_input.setObjectName("x2_input")
        self.picture = QtWidgets.QLabel(Form)
        self.picture.setGeometry(QtCore.QRect(30, 30, 341, 131))
        self.picture.setText("")
        self.picture.setTextFormat(QtCore.Qt.RichText)
        self.picture.setPixmap(QtGui.QPixmap("images/manipulator diagram.png"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.simulation_outputs = QtWidgets.QGroupBox(Form)
        self.simulation_outputs.setGeometry(QtCore.QRect(60, 510, 741, 151))
        self.simulation_outputs.setObjectName("simulation_outputs")
        self.path_dynamics_equation = QtWidgets.QLabel(self.simulation_outputs)
        self.path_dynamics_equation.setGeometry(QtCore.QRect(110, 80, 391, 31))
        self.path_dynamics_equation.setObjectName("path_dynamics_equation")
        self.path_dynamics_label = QtWidgets.QLabel(self.simulation_outputs)
        self.path_dynamics_label.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.path_dynamics_label.setObjectName("path_dynamics_label")
        self.robot_dynamics_label = QtWidgets.QLabel(self.simulation_outputs)
        self.robot_dynamics_label.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.robot_dynamics_label.setObjectName("robot_dynamics_label")
        self.dynamical_equations = QtWidgets.QLabel(self.simulation_outputs)
        self.dynamical_equations.setGeometry(QtCore.QRect(130, 30, 391, 31))
        self.dynamical_equations.setObjectName("dynamical_equations")
        self.advanced_sim_output_button = QtWidgets.QPushButton(self.simulation_outputs)
        self.advanced_sim_output_button.setGeometry(QtCore.QRect(630, 90, 91, 31))
        self.advanced_sim_output_button.setObjectName("advanced_sim_output_button")
        self.run_button = QtWidgets.QPushButton(Form)
        self.run_button.setGeometry(QtCore.QRect(670, 680, 121, 41))
        self.run_button.setCheckable(False)
        self.run_button.setObjectName("run_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.robot_parameters.setTitle(_translate("Form", "Robot parameters"))
        self.robot_parameters_box.setTitle(_translate("Form", "Link Lengths:"))
        self.l1_input.setText(_translate("Form", "0.1"))
        self.l2_input.setText(_translate("Form", "0.1"))
        self.l1_label.setText(_translate("Form", "l1"))
        self.l2_label.setText(_translate("Form", "l2"))
        self.joint_masses.setTitle(_translate("Form", "joint masses"))
        self.m1_input.setText(_translate("Form", "0.2"))
        self.m2_input.setText(_translate("Form", "0.2"))
        self.m2_label.setText(_translate("Form", "m2"))
        self.m1_label.setText(_translate("Form", "m1"))
        self.torque_limits.setTitle(_translate("Form", "Joint torque limits"))
        self.input1_min_input.setText(_translate("Form", "-2"))
        self.input1_max_input.setText(_translate("Form", "2"))
        self.input2_min_input.setText(_translate("Form", "-2"))
        self.input2_max_input.setText(_translate("Form", "2"))
        self.input1_label.setText(_translate("Form", "τ_1"))
        self.input2_label.setText(_translate("Form", "τ_2"))
        self.input1_min_label.setText(_translate("Form", "min:"))
        self.input2_min_label.setText(_translate("Form", "min:"))
        self.input1_max_label.setText(_translate("Form", "max:"))
        self.input2_max_label.setText(_translate("Form", "max:"))
        self.simulation_parameters.setTitle(_translate("Form", "simulation parameters"))
        self.path_dynamics_section.setTitle(_translate("Form", "Path Dynamics Analysis"))
        self.s_min_input.setText(_translate("Form", "0"))
        self.s_max_input.setText(_translate("Form", "1"))
        self.s_min_label.setText(_translate("Form", "s_min"))
        self.s_max_label.setText(_translate("Form", "s_max:"))
        self.s_increment_label.setText(_translate("Form", "increment"))
        self.s_increment_input.setText(_translate("Form", "0.05"))
        self.advanced_sim_button.setText(_translate("Form", "Advanced"))
        self.sdot_min_label.setText(_translate("Form", "sdot_min"))
        self.sdot_increment_label.setText(_translate("Form", "increment"))
        self.sdot_increment_label_2.setText(_translate("Form", "sdot_max"))
        self.sdot_min_input.setText(_translate("Form", "0"))
        self.sdot_increment_input.setText(_translate("Form", "0.1"))
        self.sdot_max_input.setText(_translate("Form", "20"))
        self.Controller_section.setTitle(_translate("Form", "Path Dynamics controller settings"))
        self.advanced_control_button.setText(_translate("Form", "Advanced"))
        self.time_optimal_control_cb.setText(_translate("Form", "time optimal control"))
        self.path_characteristics.setTitle(_translate("Form", "Path Characteristics"))
        self.advanced_path_button.setText(_translate("Form", "Advanced settings"))
        self.straightline_definition_settings.setTitle(_translate("Form", "Straight line definition"))
        self.x2_label.setText(_translate("Form", "x2"))
        self.y1_input.setText(_translate("Form", "0.1"))
        self.y2_input.setText(_translate("Form", "0.2"))
        self.y1_label.setText(_translate("Form", "y1"))
        self.y2_label.setText(_translate("Form", "y2"))
        self.x1_label.setText(_translate("Form", "x1"))
        self.x1_input.setText(_translate("Form", "0.1"))
        self.x2_input.setText(_translate("Form", "0.1"))
        self.simulation_outputs.setTitle(_translate("Form", "Simulation outputs"))
        self.path_dynamics_equation.setText(_translate("Form", "output dynamical equation on path"))
        self.path_dynamics_label.setText(_translate("Form", "Path Dynamics:"))
        self.robot_dynamics_label.setText(_translate("Form", "robot Dynamics:"))
        self.dynamical_equations.setText(_translate("Form", "dynamical equations"))
        self.advanced_sim_output_button.setText(_translate("Form", "Advanced"))
        self.run_button.setText(_translate("Form", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

